<?xml version="1.0"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	version="1.0">

	<!-- 
		Pass in one or multiple tags at the //request/portal node level
		Example  |theme|  |action|action-registry|  
	-->
	
	<xsl:output method="html" version="1.0" encoding="UTF-8"
		indent="yes" />

	<!--  override the built-in template to output text nodes -->
	<xsl:template match="text()" />

	<!--  eliminate comments -->
	<xsl:template match="comment()" />

	<xsl:template match="/">
		<html>
			<head>
				<style type="text/css">body { font:normal 68% verdana,arial,helvetica; color:#000000; } table tr td, table tr th { font-size: 68%; } table.details tr th{ font-weight: bold; text-align:left; background:#a6caf0; } table.details tr td{ background:#eeeee0; } p { line-height:1.5em; margin-top:0.5em; margin-bottom:1.0em; } h1 { margin: 0px 0px 5px; font: 165% verdana,arial,helvetica } h2 { margin-top: 1em; margin-bottom: 0.5em; font: bold 125% verdana,arial,helvetica } h3 { margin-bottom: 0.5em; font: bold 115% verdana,arial,helvetica } h4 { margin-bottom: 0.5em; font: bold 100% verdana,arial,helvetica } h5 { margin-bottom: 0.5em; font: bold 100% verdana,arial,helvetica } h6 { margin-bottom: 0.5em; font: bold 100% verdana,arial,helvetica } .Error { font-weight:bold; color:red; } .Failure { font-weight:bold; color:purple; }</style> 
			</head>
			<body>
				<xsl:apply-templates />
				<font style="font-size:9">
      			  <br/>Generated by BladeLogic Application Release Automation. 
     			</font>
			</body>
		</html>
	</xsl:template>
	
	<!--  
	<xsl:template match="info">
	  <h4>
		 <xsl:value-of select="endTime" />
	  </h4>
	</xsl:template>
	-->
	
	<!--  copy the top level request and attrs -->
	<xsl:template match="section">

        <div>
    		<div align="center">
       			<h2>
           			<xsl:value-of select="title" />
      			</h2>
      		</div>
      		<!-- <div align="right">	
		   		<xsl:value-of select="../info/endTime" />
	  		</div> -->
	 	</div>
		
		<h4>
			<xsl:apply-templates select="table" />
		</h4>
				
	</xsl:template>

	<xsl:template match="table">
		<xsl:choose>
		
		<xsl:when test="count(row) = 0">
			Nothing Changed
		</xsl:when>
		<xsl:otherwise>	
		<table class="details" border="0" cellpadding="5" cellspacing="2" width="95%">
		<xsl:apply-templates select="column" />
		
		<xsl:apply-templates select="row" />
		</table>
		</xsl:otherwise>
		</xsl:choose>
	</xsl:template>

	<xsl:template match="column">
		<tr><xsl:apply-templates select="name" /></tr>
	</xsl:template>

	<xsl:template match="row">
		<tr>
		 <xsl:apply-templates select="cell" />
		</tr>
	</xsl:template>
	
	<xsl:template match="name">
		<th><xsl:value-of select="text()" /></th>
	</xsl:template>	
	
	<xsl:template match="cell">
			<td><xsl:value-of select="text()" /></td>
	</xsl:template>
</xsl:stylesheet>
